apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: radiant-petclinic-pdb
  namespace: radiant-petclinic
spec:
  minAvailable: 1

  selector:
    matchLabels:
      app: radiant-petclinic