apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: radiant-petclinic-runtime-observability
spec:
  kprobes:
    - call: "sys_execve"
      syscall: true
      return: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchNamespaces:
            - namespace: radiant-petclinic