apiVersion: v1
kind: Service
metadata:
  name: radiant-petclinic-service
  namespace: radiant-petclinic
spec:
  selector:
    app: radiant-petclinic
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
